version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
